### ISSUE TITLE
Interest debt is capped after a year

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#107]
https://github.com/code-423n4/2021-04-vader-findings/issues/219

**Comment by 0x1d00ffff** [comment]
I suggest a nofix for this, since the function in question (`getInterestOwed`) is only called by `payInterest` which will be called once per era (one day). This value can be changed by the DAO but I cannot see it being extended to periods as long as a year.

Notably, the getInterestOwed function is currently capping the maximum value returned by the very first call to `payInterest` for a particular collateral/debt combination. During this call mapCollateralAsset_NextEra is uninitialized, causing _timeElapsed to equal block.timestamp (an unintentionally large value). getInterestOwed then will return a large number and payout more interest than intended.
