### ISSUE TITLE
getAnchorPrice potentially returns the wrong median

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#117]
https://github.com/code-423n4/2021-04-vader-findings/issues/213

**Comment by 0x1d00ffff** [comment]
I believe this is a `wontfix`, since the protocol is designed to launch with 5 anchors. If this is the case, the only risk is failed transactions (and other potential calculation issues) during the short time window before all 5 anchors are defined. From that time forward any risk is void. 

Any change from the current spec will likely increase gas costs, so a fix should be weighed with this in mind.

**Comment by 0x1d00ffff** [comment]
add a PR with a potential fix #160 . it does use more gas than the original
